version: '3.8'

services:
  hapi:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    ports:
      - "8080:8080"
    environment:
      - "hapi.fhir.subscription.resthook_enabled=true"
    networks:
      - fhir-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - fhir-net

  fhir-callback:
    build: ./callback-service
    container_name: fhir-callback
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      - fhir-net

networks:
  fhir-net:
    driver: bridge
    name: fhir-net

